import Link from 'next/link';
import { AsterismRule } from '@/components/asterism-rule';

export const metadata = {
  title: 'About the Atlas',
};

export default function AboutPage() {
  return (
    <div className="article-grid">
      <div className="article-margin" aria-hidden>
        Editor's note
      </div>

      <article style={{ minWidth: 0 }}>
        <p className="margin-note" style={{ color: 'var(--accent)' }}>
          About
        </p>
        <h1 className="title" style={{ fontSize: 'clamp(2rem, 5vw, 3.2rem)' }}>
          A reference work for things that never were.
        </h1>

        <AsterismRule />

        <p>
          The Atlas of Nowhere is an encyclopedia of fictional places, people,
          events, ideas, and species. Every entry is generated by a language
          model on first request and then preserved in the archive — so the
          same fake fact returns to every later visitor unchanged. Entries link
          to each other; click any blue word and the Atlas will write the page
          it points to.
        </p>

        <h2 className="section">What this is not</h2>
        <p>
          It is not a source of information. Nothing in any entry corresponds
          to a real person, place, or event. Treat it as you would a book of
          short fiction or a worldbuilding exercise — interesting, sometimes
          beautiful, never reliable.
        </p>

        <h2 className="section">What it refuses</h2>
        <p>
          The Atlas declines to write entries about real living public figures,
          real recent tragedies, or any topic for which a fictionalized treatment
          would be misleading or harmful. Such requests return a brief
          editorial note in place of an article.
        </p>

        <h2 className="section">Credits</h2>
        <p>
          Made by{' '}
          <Link href="https://github.com/" className="ink-link">
            Briant Jasper
          </Link>
          . Articles written by Anthropic Claude (Sonnet 4.6); cheaper
          operations by Groq (Llama 3.3 70B). Type set in Fraunces and Source
          Serif 4.
        </p>
      </article>

      <aside className="article-aside" aria-hidden />
    </div>
  );
}
