import type { Metadata } from 'next';
import { Fraunces, Source_Serif_4, JetBrains_Mono } from 'next/font/google';
import { Nav } from '@/components/nav';
import { AuroraBackground } from '@/components/aurora-background';
import { ReadingProgress } from '@/components/reading-progress';
import { CommandPalette } from '@/components/command-palette';
import { ShortcutsOverlay } from '@/components/shortcuts-overlay';
import { ScrollReveal } from '@/components/scroll-reveal';
import { ThemeProvider, THEME_INIT_SCRIPT } from '@/components/theme-provider';
import { getSiteUrlStatic } from '@/lib/site-url';
import './globals.css';

const fraunces = Fraunces({
  subsets: ['latin'],
  variable: '--font-display',
  display: 'swap',
  axes: ['opsz', 'SOFT'],
});

const sourceSerif = Source_Serif_4({
  subsets: ['latin'],
  variable: '--font-body',
  display: 'swap',
});

const jetbrains = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap',
});

const SITE_NAME = process.env.NEXT_PUBLIC_SITE_NAME ?? 'Atlas of Nowhere';
const SITE_URL = getSiteUrlStatic();

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} — an encyclopedia of things that don't exist`,
    template: `%s · ${SITE_NAME}`,
  },
  description:
    'A fictional encyclopedia, generated by AI, of places, people, events, and ideas that never were. Click any link to discover a new entry.',
  openGraph: {
    type: 'website',
    siteName: SITE_NAME,
    locale: 'en_US',
  },
  twitter: { card: 'summary_large_image' },
  robots: { index: true, follow: true },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} ${sourceSerif.variable} ${jetbrains.variable}`}
      suppressHydrationWarning
    >
      <head>
        {/* Pre-hydration: set data-theme synchronously to avoid FOUC. */}
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
      </head>
      <body>
        <ThemeProvider>
          <AuroraBackground />
          <ReadingProgress />
          <Nav />
          <main id="main">{children}</main>
          <footer className="read-col" style={{ paddingBlock: '4rem 2rem' }}>
            <div className="margin-note" style={{ textAlign: 'center' }}>
              {SITE_NAME} · transmitted from nowhere in particular
            </div>
          </footer>
          <CommandPalette />
          <ShortcutsOverlay />
          <ScrollReveal />
        </ThemeProvider>
      </body>
    </html>
  );
}
