export function DisclaimerBanner() {
  return (
    <div
      role="note"
      aria-label="Fictional content disclaimer"
      className="disclaimer"
    >
      <span className="seal" aria-hidden />
      <span>
        Fictional entry. Generated by a language model. Nothing here is real.
      </span>
    </div>
  );
}
