import type { Metadata } from 'next';
import { notFound, redirect } from 'next/navigation';
import { eq, sql } from 'drizzle-orm';
import { db, schema } from '@/lib/db/client';
import { isValidSlug, slugToTitle, titleToSlug } from '@/lib/slug';
import { plateNumber } from '@/lib/design/plate-number';
import { ArticleView } from '@/components/article-view';
import { Infobox } from '@/components/infobox';
import { DisclaimerBanner } from '@/components/disclaimer-banner';
import { StreamingArticle } from '@/components/streaming-article';
import { ArticleToc } from '@/components/article-toc';

type Params = { slug: string };

const SITE_NAME = process.env.NEXT_PUBLIC_SITE_NAME ?? 'Atlas of Nowhere';
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000';

async function getArticle(slug: string) {
  return db
    .select()
    .from(schema.articles)
    .where(eq(schema.articles.slug, slug))
    .limit(1)
    .then((rows) => rows[0] ?? null);
}

export async function generateMetadata({
  params,
}: {
  params: Promise<Params>;
}): Promise<Metadata> {
  const { slug } = await params;
  if (!isValidSlug(slug)) return { title: 'Not found' };

  const row = await getArticle(slug);
  const title = row?.title ?? slugToTitle(slug);
  const description = row?.summary ?? `An entry in ${SITE_NAME}.`;
  const url = `${SITE_URL}/wiki/${slug}`;

  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      type: 'article',
      siteName: SITE_NAME,
    },
    twitter: { card: 'summary_large_image', title, description },
  };
}

export default async function ArticlePage({
  params,
  searchParams,
}: {
  params: Promise<Params>;
  searchParams: Promise<{ from?: string }>;
}) {
  const { slug } = await params;
  const { from } = await searchParams;

  if (!isValidSlug(slug)) {
    // Try to coerce a near-slug ("Belgian Sock Riots") into the canonical form.
    const coerced = titleToSlug(decodeURIComponent(slug));
    if (coerced && coerced !== slug) redirect(`/wiki/${coerced}`);
    notFound();
  }

  const row = await getArticle(slug);

  if (row) {
    db.update(schema.articles)
      .set({ hits: sql`${schema.articles.hits} + 1` })
      .where(eq(schema.articles.slug, slug))
      .catch(() => {
        /* counter is best-effort */
      });

    const ldjson = {
      '@context': 'https://schema.org',
      '@type': 'CreativeWork',
      headline: row.title,
      description: row.summary,
      datePublished: row.createdAt.toISOString(),
      url: `${SITE_URL}/wiki/${row.slug}`,
      author: { '@type': 'Organization', name: SITE_NAME },
      isAccessibleForFree: true,
      genre: 'fiction',
      disclaimer:
        'This article is fictional and was generated by a large language model. None of its contents represent real persons, places, or events.',
    };

    return (
      <div className="article-grid">
        <div className="article-margin" aria-hidden>
          {row.title.toUpperCase().slice(0, 36)}
          <br />— Pl. {plateNumber(row.slug)}
          <br />
          <span style={{ color: row.degraded ? 'var(--accent)' : 'var(--ink-soft)' }}>
            {row.degraded ? 'Draft mode' : 'Final'}
          </span>
        </div>

        <article style={{ minWidth: 0 }}>
          <div
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'baseline',
              marginBottom: '1.25rem',
              gap: '1rem',
              flexWrap: 'wrap',
            }}
          >
            <DisclaimerBanner />
            <span className="plate-number">Plate {plateNumber(row.slug)}</span>
          </div>

          <ArticleView html={row.contentHtml} />

          <footer style={{ marginTop: '4rem', borderTop: '1px solid var(--rule)', paddingTop: '1.5rem' }}>
            <p className="margin-note">
              Plate transmitted from the Atlas on{' '}
              {row.createdAt.toISOString().slice(0, 10)} · {row.provider} · {row.model}
            </p>
          </footer>

          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(ldjson) }}
          />
        </article>

        <aside className="article-aside">
          <ArticleToc />
          <Infobox article={row.contentJson} />
        </aside>
      </div>
    );
  }

  // Cache miss → stream-generate.
  return (
    <div className="article-grid">
      <div className="article-margin" aria-hidden>
        New plate
        <br />— Pl. {plateNumber(slug)}
      </div>

      <article style={{ minWidth: 0 }}>
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'baseline',
            marginBottom: '1.25rem',
            gap: '1rem',
            flexWrap: 'wrap',
          }}
        >
          <DisclaimerBanner />
          <span className="plate-number">Plate {plateNumber(slug)}</span>
        </div>

        <StreamingArticle slug={slug} parentSlug={from} />
      </article>

      <aside className="article-aside" aria-hidden />
    </div>
  );
}
